version: '2'

services:
  webserver:
    build: ./docker/webserver
    ports:
      - "80:80"
      - "443:443"
    links:
      - db

  db:
    build: ./docker/db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=docker
